/*
PROJETO 
GESTÃO DE VENDAS DE LOJA DE INSTRUMENTOS 
TABELAS 
*/

CREATE DATABASE LOJA_MUSICAL
GO

USE LOJA_MUSICAL
GO

CREATE TABLE PRODUTO
(
	 ID_PRODUTO TINYINT IDENTITY NOT NULL
	,DESCRICAO VARCHAR(100) NOT NULL
	,QTD INT NOT NULL
	,ID_MARCA TINYINT NOT NULL
	,ID_CATEGORIA TINYINT NOT NULL
	,VALOR DECIMAL(8,2) NOT NULL
)
GO

CREATE TABLE MARCA
(
	 ID_MARCA TINYINT IDENTITY NOT NULL
	,MARCAR VARCHAR(60) NOT NULL
)

CREATE TABLE CATEGORIA
(
	ID_CATEGORIA TINYINT IDENTITY NOT NULL
	,CATEGORIA VARCHAR(60)
)

CREATE TABLE PEDIDO_VENDA
(
	 COD_VENDA INT NOT NULL
	,COD_SEQ INT NOT NULL
	,ID_VENDEDOR VARCHAR(60) NOT NULL
	,ID_PRODUTO TINYINT NOT NULL
	,ID_CLIENTE TINYINT NOT NULL
	,QTD INT NOT NULL
	,VALOR_UNITARIO DECIMAL(8,2) NOT NULL
	,VALOR_TOTAL DECIMAL(8,2)  NOT NULL
	,STATUS_PEDITO VARCHAR(10) NOT NULL
	,DATA_PEDITO DATETIME NOT NULL

)
GO

CREATE TABLE VENDA 
(
	 COD_VENDA INT NOT NULL
	,ID_CLIENTE TINYINT NOT NULL
	,ID_VENDEDOR TINYINT NOT NULL
	,DATA_VENDA DATETIME NOT NULL
	,VALOR_TOTAL DECIMAL(8,2) NOT NULL
)
GO

CREATE TABLE CLIENTE 
(
	 ID_CLIENTE TINYINT IDENTITY NOT NULL
	,NOME VARCHAR(100) NOT NULL 
	,EMAIL VARCHAR(60) NOT NULL
	,CPF CPF NOT NULL
	,FONE CELULAR  NOT NULL
)
GO

CREATE TABLE VENDEDORES 
(
	 ID_VENDEDOR TINYINT IDENTITY NOT NULL
	,NOME VARCHAR(100) NOT NULL
	,SALARIO DECIMAL(8,2) NOT NULL
)
